language: generic

os:
  - osx

matrix:
  include:
    ##############
    # Emacs 26.X #
    ##############
    # Emacs 26.x on Sierra      (macOS 10.12 - xcode9.2)
    - env:
      - BUILD_OPTIONS=""
      - TEST_OPTIONS=""
      osx_image: xcode9.2
    # Emacs 26.x on High Sierra (macOS 10.13 - xcode10.1)
    - env:
      - BUILD_OPTIONS=""
      - TEST_OPTIONS=""
      osx_image: xcode10.1
    # Emacs 26.x on Mojave      (macOS 10.14 - xcode10.3)
    - env:
      - BUILD_OPTIONS=""
      - TEST_OPTIONS=""
      osx_image: xcode10.3
    # Emacs 26.x on Mojave      (macOS 10.14 - xcode11.0)
    - env:
      - BUILD_OPTIONS=""
      - TEST_OPTIONS=""
      osx_image: xcode11.0
    # Emacs 26.x on Sierra      (macOS 10.12 - xcode9.2) - All options (imagemagick@6)
    - env:
      - BUILD_OPTIONS="--with-cocoa --with-no-frame-refocus --with-imagemagick --with-multicolor-fonts"
      - TEST_OPTIONS=""
      osx_image: xcode9.2
    # Emacs 26.x on High Sierra (macOS 10.13 - xcode10.1) - All options (imagemagick@6)
    - env:
      - BUILD_OPTIONS="--with-cocoa --with-no-frame-refocus --with-imagemagick --with-multicolor-fonts"
      - TEST_OPTIONS=""
      osx_image: xcode10.1
    # Emacs 26.x on Mojave      (macOS 10.14 - xcode10.3) - All options (imagemagick@6)
    - env:
      - BUILD_OPTIONS="--with-cocoa --with-no-frame-refocus --with-imagemagick --with-multicolor-fonts"
      - TEST_OPTIONS=""
      osx_image: xcode10.3
    # Emacs 26.x on Mojave      (macOS 10.14 - xcode11.0) - All options (imagemagick@6)
    - env:
      - BUILD_OPTIONS="--with-cocoa --with-no-frame-refocus --with-imagemagick --with-multicolor-fonts"
      - TEST_OPTIONS=""
      osx_image: xcode11.0
    ##############
    # Emacs 27.X #
    ##############
    # Emacs 27.x on Sierra      (macOS 10.12 - xcode9.2) - All options except pdumper (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode9.2
    # Emacs 27.x on High Sierra (macOS 10.13 - xcode10.1) - All options except pdumper (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode10.1
    # Emacs 27.x on Mojave      (macOS 10.14 - xcode10.3) - All options except pdumper (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode10.3
    # Emacs 27.x on Mojave      (macOS 10.14 - xcode11.0) - All options except pdumper (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode11.0
    # Emacs 27.x on Sierra      (macOS 10.12 - xcode9.2) - All options (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-pdumper --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode9.2
    # Emacs 27.x on High Sierra (macOS 10.13 - xcode10.1) - All options (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-pdumper --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode10.1
    # Emacs 27.x on Mojave      (macOS 10.14 - xcode10.3) - All options (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-pdumper --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode10.3
    # Emacs 27.x on Mojave      (macOS 10.14 - xcode11.0) - All options (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-pdumper --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode11.0

  fast_finish: true

before_install:
  - brew update

script:
  - travis_wait 50 brew install Formula/emacs-head.rb $BUILD_OPTIONS
  - brew test $TEST_OPTIONS Formula/emacs-head.rb
