language: generic

os:
  - osx

jobs:
  include:
    ##############
    # Emacs 26.X #
    ##############
    # Emacs 26.x on High Sierra (macOS 10.13 - xcode10.1)
    - env:
      - BUILD_OPTIONS=""
      - TEST_OPTIONS=""
      osx_image: xcode10.1
    # Emacs 26.x on Mojave      (macOS 10.14 - xcode11.3)
    - env:
      - BUILD_OPTIONS=""
      - TEST_OPTIONS=""
      osx_image: xcode11.3
    # Emacs 26.x on High Sierra (macOS 10.13 - xcode10.1) - All options (imagemagick@6)
    - env:
      - BUILD_OPTIONS="--with-cocoa --with-no-frame-refocus --with-imagemagick --with-multicolor-fonts"
      - TEST_OPTIONS=""
      osx_image: xcode10.1
    # Emacs 26.x on Mojave      (macOS 10.14 - xcode11.3) - All options (imagemagick@6)
    - env:
      - BUILD_OPTIONS="--with-cocoa --with-no-frame-refocus --with-imagemagick --with-multicolor-fonts"
      - TEST_OPTIONS=""
      osx_image: xcode11.3
    ##############
    # Emacs 28.X #
    ##############
    # Emacs 28.x on High Sierra (macOS 10.13 - xcode10.1) - All options except pdumper (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode10.1
    # Emacs 28.x on Mojave      (macOS 10.14 - xcode11.3) - All options except pdumper (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode11.3
    # Emacs 28.x on High Sierra (macOS 10.13 - xcode10.1) - All options (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-pdumper --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode10.1
    # Emacs 28.x on Mojave      (macOS 10.14 - xcode11.3) - All options (imagemagick@7)
    - env:
      - BUILD_OPTIONS="--HEAD --with-cocoa --with-no-frame-refocus --with-imagemagick --with-jansson --with-pdumper --with-xwidgets"
      - TEST_OPTIONS="--HEAD"
      osx_image: xcode11.3

  fast_finish: true

before_install:
  - brew update
  - brew unlink python@2

script:
  - travis_wait 50 brew install Formula/emacs-head.rb $BUILD_OPTIONS
  - brew test $TEST_OPTIONS Formula/emacs-head.rb
