name: Emacs 27

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'Formula/emacs-head@27.rb'
      - 'patches/**'
      - '.github/workflows/emacs-27.yml'
  pull_request:
    paths:
      - 'Formula/emacs-head@27.rb'
      - 'patches/**'
      - '.github/workflows/emacs-27.yml'
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
        build_opts:
          # Bottle
          - ''
          # All options (imagemagick@7)
          - '--with-cocoa --with-no-frame-refocus --with-imagemagick --with-pdumper --with-xwidgets'

    env:
      HOMEBREW_GITHUB_REF: ${{ github.head_ref || github.ref }}
      HOMEBREW_GITHUB_REPOSITORY: ${{ github.repository }}
      HOMEBREW_GITHUB_ACTOR: ${{ github.actor }}

    steps:
    - uses: actions/checkout@v1

    - name: Use XCode 12.2 for Big Sur
      if: contains(matrix.os, 'macos-11.0')
      run: sudo xcode-select -s "/Applications/Xcode_12.2.app"

    - name: Build emacs-head@27 ${{ matrix.build_opts }}
      run: brew install --verbose emacs-head@27.rb ${{ matrix.build_opts }}
      working-directory: Formula

    - name: Test installation
      run: brew test emacs-head@27.rb
      working-directory: Formula
