name: Emacs 28

on:
  push:
    branches:
      - master
      - dev
      - feature/native-comp
    paths:
      - 'Formula/emacs-head@28.rb'
      - 'patches/**'
      - '.github/workflows/emacs-28.yml'
  pull_request:
    paths:
      - 'Formula/emacs-head@28.rb'
      - 'patches/**'
      - '.github/workflows/emacs-28.yml'
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        build_opts:
          # No Options --> TO BE UNCOMMENTED
          # - ''
          # All options (imagemagick@7)
          # - '--with-cocoa --with-no-frame-refocus --with-imagemagick --with-pdumper --with-xwidgets' --> TO BE UNCOMMENTED
          # All options (imagemagick@7) + native-comp support
          - '--with-cocoa --with-no-frame-refocus --with-imagemagick --with-pdumper --with-xwidgets --with-native-comp'

    env:
      HOMEBREW_GITHUB_REF: ${{ github.head_ref || github.ref }}
      HOMEBREW_GITHUB_REPOSITORY: ${{ github.repository }}
      HOMEBREW_GITHUB_ACTOR: ${{ github.actor }}

    steps:
    - uses: actions/checkout@v1

    - name: Install gcc with jit support
      if: contains(matrix.build_opts, '--with-native-comp') == true
      run: brew install gcc.rb --build-from-source --force
      working-directory: Formula

    - name: Build emacs-head@28 ${{ matrix.build_opts }}
      run: brew install --verbose emacs-head@28.rb ${{ matrix.build_opts }}
      working-directory: Formula

    - name: Test installation
      run: brew test emacs-head@28.rb
      working-directory: Formula
